---
# handlers file for setup-apache

    - name: start_httpd
      service:
        name: httpd
        state: started
    # when: ansible_os_family == "RedHat"

    - name: start_apache2
      service:
        name: apache2
        state: started
    # when: ansible_os_family == "Debian"

    - name: restart_httpd
      service:
        name: httpd
        state: restarted

    - name: restart_apache2
      service:
        name: apache2
        state: restarted

