---
- name: "This Playbook is for installing httpd/apache in all managed nodes"
  hosts: all
  become: true
  tasks:
    - name: "Install httpd"
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"
    - name: "start httpd service"
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
    - name: "Install apache2"
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
    - name: "Start apache2 service"
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: index.html
      copy:
        src: /opt/ansible/index.html
        dest: /var/www/html/
        mode: 0666
