---
- name: "Install httpd in Webservers"
  hosts: webservers
  become: true
  tasks:
    - name: "Install httpd"
      yum:
        name: httpd
        state: installed
          
    - name: "start httpd service"
      service:
        name: httpd
        state: started
